### ISSUE TITLE
raw_info values in provider auth is nil

### ISSUE THREAD

**Issue by SudhagarS** [arunagw/omniauth-twitter#101]
We get the provider auth and store it in the db. Some users have reported a issue that their page is not rendering properly. When we inspected the values in the db for one such user, it was this

:twitterAuth=>"{\"twitterId\":\"XXX\",\"twitterAccessToken\":\"XXX\",\"twitterAccessTokenSecret\":\"XXX\",\"twitterScreenName\":null,\"twitterDescription\":null,\"twitterFollowersCount\":null,\"twitterFriendsCount\":null,\"twitterListedCount\":null,\"twitterLocation\":null,\"twitterName\":null,\"twitterProfileImageUrl\":null,\"twitterProfileImageUrlHttps\":null,\"twitterUrl\":null,\"twitterStatusesCount\":null,\"twitterUtcOffset\":null,\"isProtected\":null,\"isTwitterVerified\":null}"

This happens very rarely and there is no pattern to it.

**Comment by raysrashmi** [comment]
@SudhagarS Closing this. If you still have this issue don't hesitate to reopen it
