### ISSUE TITLE
OAuth::Unauthorized (400 Bad Request)

### ISSUE THREAD

**Issue by ArielAleksandrus** [arunagw/omniauth-twitter#105]
I'm getting this error in Development. Is there a problem with setting 0.0.0.0:3000 as the domain of the callback?

This is what I'm getting

> 
> OAuth::Unauthorized (400 Bad Request):
>   oauth (0.5.1) lib/oauth/consumer.rb:217:in `token_request'
>   oauth (0.5.1) lib/oauth/consumer.rb:136:in `get_request_token'
>   omniauth-oauth (1.1.0) lib/omniauth/strategies/oauth.rb:28:in `request_phase'
>   omniauth-twitter (1.2.1) lib/omniauth/strategies/twitter.rb:61:in `request_phase'
>   omniauth (1.3.1) lib/omniauth/strategy.rb:215:in `request_call'
>   omniauth (1.3.1) lib/omniauth/strategy.rb:183:in `call!'
> 

My **devise.rb** has this line:

`config.omniauth :twitter, setup: true`

And in the setup method, in a controller, I have these lines

```
env['omniauth.strategy'].options[:client_id] = id
env['omniauth.strategy'].options[:client_secret] = token
```

The variables "id" and "token" correctly matches my Twitter application's credentials.

What could be the problem?

**Comment by raysrashmi** [comment]
Hi Ariel, I assume that by id and token means is api_key and api_secret right?

**Comment by ArielAleksandrus** [comment]
yes, that's the way I called them. variable "id" is the App Id, and "token" is the App Secret. The values match my credentials correctly. I don't understand what's going on that I'm getting error 400. By the way, this is happening with LinkedIn gem as well, whereas with Facebook and Google I'm having no issues.

**Comment by raysrashmi** [comment]
Then I guess Its not omniauth twitter issues you have some problem in your request. May be ask to stackoverflow. or if you can push an sample app where I can check

**Comment by ArielAleksandrus** [comment]
https://github.com/ArielAleksandrus/issuetwitteromniauth

Here is a sample rails app that is throwing this very error

![screenshot from 2016-06-02 15-39-32](https://cloud.githubusercontent.com/assets/10962902/15756632/78b295ce-28d8-11e6-80fa-3aef8472fb6a.png)

**Comment by raysrashmi** [comment]
I found that the keys name should be `consumer_key` and `consumer_secret`.
`
 request.env['omniauth.strategy'].options[:consumer_key]
 request.env['omniauth.strategy'].options[:consumer_secret]
`

**Comment by ArielAleksandrus** [comment]
Thank you! That solves the issue

**Comment by vkeziah** [comment]
Thank you @raysrashmi , It worked for me
