### ISSUE TITLE
Update omniauth_oauth to omniauth_oauth2

### ISSUE THREAD

**Issue by thiagovsk** [arunagw/omniauth-twitter#106]
Hello Guys!

I'am  developing one application which use many providers to sign in, like facebook, gmail, twitter, github...

I noticed that only omniauth-twitter doesn't use omniauht-oauth2 , is there any special reason for that?

Is there anyway, I can contribute to update omniauth-oauth to omniauth-oauth2, if it is possible.

Best regards.

**Comment by arunagw** [comment]
Hey @thiagovsk thanks for info! Seems like this is possible and someone posted a gist as well https://gist.github.com/cavneb/4afc7ec0beaad30f4015

I think it's better to have new gem instead of changing this one.. What do you think?

**Comment by raysrashmi** [comment]
@thiagovsk Hey are you working on this? If not can I start with this?

**Comment by thiagovsk** [comment]
@arunagw looks good to me =D

@raysrashmi I'am not working on this, feel free to start, and I will be happy in help with anything.
