### ISSUE TITLE
issue d to flume

### ISSUE THREAD

**Issue by abhi1995** [arunagw/omniauth-twitter#109]
16/09/22 10:47:33 INFO twitter4j.TwitterStreamImpl: Establishing connection.
16/09/22 10:47:36 INFO twitter4j.TwitterStreamImpl: 401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 401 Unauthorized</title>
</head>
<body>

<h2>HTTP ERROR: 401</h2>

<p>Problem accessing '/1.1/statuses/sample.json?stall_warnings=true'. Reason:

<pre>    Unauthorized</pre>

</body>
</html>

16/09/22 10:47:36 ERROR twitter.TwitterSource: Exception while streaming tweets
401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 401 Unauthorized</title>
</head>
<body>

<h2>HTTP ERROR: 401</h2>

<p>Problem accessing '/1.1/statuses/sample.json?stall_warnings=true'. Reason:

<pre>    Unauthorized</pre>

</body>
</html>

solve this issue facing from three days...

**Comment by shanemeister** [comment]
Did anyone ever resolve this issue? I am having the same problem. Any feedback is appreciated.

**Comment by arunagw** [comment]
Seems like issue with Twitter gem? Are you able to access other information via auth tokens?

**Comment by raysrashmi** [comment]
Closing it for now. Feel free to reopen if it happens again
