### ISSUE TITLE
Support for Ruby 2.4

### ISSUE THREAD

**Issue by SamSaffron** [arunagw/omniauth-twitter#112]
Re:

``` 
s.add_dependency 'json', '~> 1.3' 
```

json on 2.4 seems to be at 2.0.2, trying to install an old json like 1.8.3 on 2.4 will fail. 

is there any reason for this explicit dependency?

**Comment by jonian** [comment]
Hi, any timeline on when a new version without json will be released?

**Comment by arunagw** [comment]
New version has been released https://rubygems.org/gems/omniauth-twitter/versions/1.3.0
