### ISSUE TITLE
OAuth::Unauthorized (401 Authorization Required)

### ISSUE THREAD

**Issue by Arslan-Ali-Butt** [arunagw/omniauth-twitter#118]
I have tried every solution out there, but still I'm unable to figure this out.

I have put the callback URL.

I'm using Rials 5.0.0.1

**Comment by gordysc** [comment]
@Arslan-Ali-Butt I had this issue, but specifying the callback url in my Twitter app fixed it.  Can you confirm if that works for you?

**Comment by Arslan-Ali-Butt** [comment]
@gordysc Earlier, I had done the same thing, but it wasn't working, but now it is. Must be something wrong on my end. Anyhow, I'm closing this issue now.

**Comment by gordysc** [comment]
Glad to hear you're unblocked!
