### ISSUE TITLE
How can I access email address ?

### ISSUE THREAD

**Issue by SidharthBansal** [arunagw/omniauth-twitter#129]
The request.env['omniauth.auth'] doesn't create email field. But stackoverflow shows that there is a way to fetch email addresses via twitter. Can anyone help me how to fetch it? I am not using devise. I have made my own login system

**Comment by truongnmt** [comment]
You have to fill your app's Privacy Policy URL and Terms of Service URL, then head to Permission tab and choose `Request email addresses from users`

**Comment by SidharthBansal** [comment]
I want to know the place where it is stored inside the hash. Is it hash[info][email]?

**Comment by truongnmt** [comment]
I'm not sure, use debug and you can find out.

**Comment by raysrashmi** [comment]
@SidharthBansal You can get the email in `request.env['omniauth.auth'][:info][:email]`
