### ISSUE TITLE
dynamic callback url

### ISSUE THREAD

**Issue by arjun-urs** [arunagw/omniauth-twitter#26]
Hey Arun,

Twitter supports dynamic oauth_callback URLs per OAuth 1.0a. It would be great if you could configure in omniauth-twitter gem for this feature.

Cheers,
Arjun Urs

**Comment by raysrashmi** [comment]
I think you can redirect user to any url by using request.env['omniauth.origin'].

https://github.com/intridea/omniauth/wiki/Saving-User-Location

**Comment by mahemoff** [comment]
This may also be useful:

OmniAuth.config.full_host = "http://example.com"

It supports callback on a different domain or port, which the omniauth.origin doesn't work for, ie if the app server is not public (behind a proxy/CDN) and therefore won't be reached by the browser after redirect.

via http://awesomeprogrammer.com/blog/2012/12/09/dealing-with-omniauth-redirect-uri-mismatch-invalid-port-number-gotcha/
