### ISSUE TITLE
timeout: Timeout::Error, execution expired

### ISSUE THREAD

**Issue by arashm** [arunagw/omniauth-twitter#43]
I can't implement omniauth-twitter in my app. I get following error:

     Started GET "/auth/twitter" for 127.0.0.1 at 2012-12-01 13:29:23 +0330
     (twitter) Request phase initiated.
     (twitter) Authentication failure! timeout: Timeout::Error, execution expired

    Timeout::Error (execution expired):
      /home/arashm/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/net/http.rb:762:in `initialize'
      /home/arashm/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/net/http.rb:762:in `open'
      /home/arashm/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/net/http.rb:762:in `block in connect'
      /home/arashm/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/net/http.rb:762:in `connect'
      /home/arashm/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
      /home/arashm/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/net/http.rb:744:in `start'
      /home/arashm/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/net/http.rb:1284:in `request'
      oauth (0.4.6) lib/oauth/consumer.rb:161:in `request'
      oauth (0.4.6) lib/oauth/consumer.rb:194:in `token_request'
      oauth (0.4.6) lib/oauth/consumer.rb:136:in `get_request_token'
      omniauth-oauth (1.0.1) lib/omniauth/strategies/oauth.rb:29:in `request_phase'
      omniauth-twitter (0.0.11) lib/omniauth/strategies/twitter.rb:50:in `request_phase'
      omniauth (1.1.0) lib/omniauth/strategy.rb:207:in `request_call'
      omniauth (1.1.0) lib/omniauth/strategy.rb:174:in `call!'
      omniauth (1.1.0) lib/omniauth/strategy.rb:157:in `call'
      omniauth (1.1.0) lib/omniauth/builder.rb:48:in `call'
      actionpack (3.2.3) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
      rack (1.4.1) lib/rack/etag.rb:23:in `call'
      rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
      actionpack (3.2.3) lib/action_dispatch/middleware/head.rb:14:in `call'
      actionpack (3.2.3) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
      actionpack (3.2.3) lib/action_dispatch/middleware/flash.rb:242:in `call'
      rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
      rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
      actionpack (3.2.3) lib/action_dispatch/middleware/cookies.rb:338:in `call'
      activerecord (3.2.3) lib/active_record/query_cache.rb:64:in `call'
      activerecord (3.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:467:in `call'
      actionpack (3.2.3) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
      activesupport (3.2.3) lib/active_support/callbacks.rb:405:in `_run__1553044154901315329__call__344883622791553659__callbacks'
      activesupport (3.2.3) lib/active_support/callbacks.rb:405:in `__run_callback'
      activesupport (3.2.3) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
      activesupport (3.2.3) lib/active_support/callbacks.rb:81:in `run_callbacks'
      actionpack (3.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
      actionpack (3.2.3) lib/action_dispatch/middleware/reloader.rb:65:in `call'
      actionpack (3.2.3) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
      actionpack (3.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
      actionpack (3.2.3) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
      railties (3.2.3) lib/rails/rack/logger.rb:26:in `call_app'
      railties (3.2.3) lib/rails/rack/logger.rb:16:in `call'
      actionpack (3.2.3) lib/action_dispatch/middleware/request_id.rb:22:in `call'
      rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
      rack (1.4.1) lib/rack/runtime.rb:17:in `call'
      activesupport (3.2.3) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
      rack (1.4.1) lib/rack/lock.rb:15:in `call'
      actionpack (3.2.3) lib/action_dispatch/middleware/static.rb:62:in `call'
      railties (3.2.3) lib/rails/engine.rb:479:in `call'
      railties (3.2.3) lib/rails/application.rb:220:in `call'
      rack (1.4.1) lib/rack/content_length.rb:14:in `call'
      railties (3.2.3) lib/rails/rack/log_tailer.rb:14:in `call'
      rack (1.4.1) lib/rack/handler/webrick.rb:59:in `service'
      /home/arashm/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
      /home/arashm/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
      /home/arashm/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

I tried codes from [Ryan Bates's railscast reposity] (https://github.com/railscasts/241-simple-omniauth-revised) but it failed again with the same error.

my app is configured for Twitter like this:
> website: 127.0.0.1
> callback url: 127.0.0.1:3000/auth/twitter/callback

**Comment by raysrashmi** [comment]
I can't see this issue now. closing this one
