### ISSUE TITLE
Twitter authentication/login issue: "There is no request token for this page..."

### ISSUE THREAD

**Issue by mmrenomeron** [arunagw/omniauth-twitter#58]
Does anyone know how to fix this issue? I keep on getting this error from Twitter when I try to login on our app. This was happening since May 23, 2013 and just for random Twitter accounts.

"Whoa there! The request token for this page is invalid. It may have already been used, or expired because it is too old. Please go back to the site or application that sent you here and try again; it was probably just a mistake."

I also saw some users experiencing this issue in this link: https://dev.twitter.com/discussions/17911 but it seems that Twitter devs haven't got back for a solution. 

Hopefully someone can help me with this matter. Thanks a lot!

**Comment by Bhavaa** [comment]
Hi.. mmrenonmeron.. Please tell what is the code to be changed

**Comment by developer-sandip** [comment]
Me too having Same issue !!!

**Comment by Nadeem-Saif** [comment]
I am also facing same issue

**Comment by okellogabrielinnocent** [comment]
@mmrenomeron, Your solution could help most of us share the idea please
