### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by deepakmani** [arunagw/omniauth-twitter#74]
Hi,

I have a twitter app using your gem. 

I use heroku to host and was able to signin until last week. This week, I receive an error both locally and in production stating 
````
401 Unauthorized
````
I did not change anything and have tried to play with the callback url by leaving it empty and with an address to no avail.

Can you please advise on what could be the issue.

Deepak

**Comment by rodrigoargumedo** [comment]
I get the same issue when before signing into twitter but I'm not sure why it is getting this error.

![omniauth](https://cloud.githubusercontent.com/assets/7613139/6352862/4616b4b4-bc0b-11e4-97fc-b89d4e848d06.PNG)

**Comment by rodrigoargumedo** [comment]
Oh, never mind. Had to add my keys for my repo.

**Comment by rodrigoargumedo** [comment]
If anyone who encounter this problem before, my possible solution to this problem would be this:

a) Add your keys into secrets.yml file (make sure you're **not** sharing this file)
``` yml 
twitter_consumer_key: [insert consumer key here]
twitter_consumer_secret: [insert consumer secret here]
```
b) Add this onto your omniauth.rb:
``` ruby
Rails.application.config.middleware.use OmniAuth::Builder do
 provider :twitter, Rails.application.secrets.twitter_consumer_key, Rails.application.secrets.twitter_consumer_secret
end
```
c) Profit.

That worked for me. Just for my two cent shot.

**Comment by Aleksandaar** [comment]
This error can happen if you don't specify a callback URL in twitter settings.
For example: http://localhost.net:3000/oauth2/callback/
where 'localhost.net' is my 0.0.0.0 address set up in the hosts

**Comment by jiggneshhgohel** [comment]
This can also happen if you use [oauth dynamic setup](https://github.com/intridea/omniauth/wiki/Setup-Phase) and you pass a custom callback url but in twitter app settings you checked the option `Enable Callback Locking`. It happened with me and unchecking the option `Enable Callback Locking` and saving the updated settings the auth started working.
