### ISSUE TITLE
Profile picture disappear after change

### ISSUE THREAD

**Issue by damienh** [arunagw/omniauth-twitter#85]
Hi,

I have an app that gets on register the auth.info.image and returns the url and add that as their profile picture. I noticed that once a user changes their image on twitter it no longer appears on my app.

Is this because I did not use this auth.extra.raw_info.profile_image_url_https? Instead.

Any information would be very much appreciated.

**Comment by ahmadajmi** [comment]
@damienh I have this issues too, I think twitter delets the old omage once the user changed his image

I fixed this by checking if the images exist and then get the new image, save it to the DB.

gems to be added to the Gemfile

```
gem 'twitter'
gem 'faraday'
```

And in my User controller Show action

``` ruby
def show

	# ......
    # ......

	# Check if the User image is exist using Faraday
	# Get User Image Using the Twitter gem
	# Save the Image to the user profile

    @user_image = @user.image

    if Faraday.head(@user_image).status != 200
      @user = params[:id] ? User.friendly.find(params[:id]) : User.friendly.find(params[:nickname])
      @user_image = $twitter.user(@user.uid.to_i).profile_image_url_https(:bigger).to_s
      @user.image = @user_image
      @user.save
    end
end
```

May be it's not the best solution ever but it serves the users and fixed the issue for the moment

**Comment by kernow** [comment]
That's going to slow down any response significantly, you'd be better off checking this in a background task

**Comment by ahmadajmi** [comment]
And that's my issue about this solution, do you mean by using a Cron job to do this.

**Comment by kernow** [comment]
It depends on your use case, if you have lots of users to check you can use something like whenever and a queue such as delayed_job. If you have very few checks to do you can use whenever only.

Another option would be to kick off a background process when the page is requested and send the image to the browser ones it's available, this would involve client side code too.

A third option is to store the profile image on your own system, this it doesn't matter if the image is removed on twitter.

**Comment by ahmadajmi** [comment]
Thanks Jamie, I think whenever will be great for this, will try this and see how it goes

**Comment by arunagw** [comment]
Closing this as this seems not an issue with omniauth-twitter.

thanks
