### ISSUE TITLE
Verify user from mobile return access token

### ISSUE THREAD

**Issue by dieuit07** [arunagw/omniauth-twitter#94]
Hi everyone. I have a problem and it take me so much time :( 
I am building Api for mobile app call. And in mobile user login twitter then call back to my server an access_token. So from this access_token, How could I call to get uid, email, username, ... Is this supported in GEM? 

Please help me

**Comment by raysrashmi** [comment]
Sorry for late reply.
Do you still have this concern?
Sorry this is not supported in this Gem. I think you can use twitter gem for this for getting user information

**Comment by dieuit07** [comment]
Thanks for reply @raysrashmi  :)
The uid and provider is supplied from ios or android, so I just verify in db and login that user
