### ISSUE TITLE
It's now possible to get user's email address from Twitter, can we do this w/omniauth-twitter?

### ISSUE THREAD

**Issue by sunild** [arunagw/omniauth-twitter#95]
Buried at the bottom of this [Twitter Developer's forum post](https://twittercommunity.com/t/how-to-get-email-from-twitter-user-using-oauthtokens/558) a Twitter employee finally reveals that you can request access to get the user's email address from this [Twitter API Policy Support](https://support.twitter.com/forms/platform) form.

It is suggested to click the "I need access to special authentication privileges (e.g. xAuth)" radio button, and explain you want access to the user's email address. A common theme seems to be that Twitter support person misunderstands/denies/redirects you somewhere else (it happened to me too). But if you ask again, they will grant you access:

> We've enabled requesting email permissions for your app. Please note that this permission is only enabled on new sign-ins to your app. In order to begin, please log into apps.twitter.com and

* Add a terms of service and privacy policy to your app info
* Change your token's scope to request email

I also found a checkbox to select in my Twitter app's settings to enable the email permission.

I'm just stuck on how I might do this properly w/omniauth-twitter. I also use devise and it's omniauthable module. I see an array of permissions being used [here](https://github.com/arunagw/omniauth-twitter/blob/master/lib/omniauth/strategies/twitter.rb#L42), just not sure what to include and what else to do.

 I apologize for dumping all of this here, but I haven't seen anyone discussing how to solve this now that it's possible.

I am happy to try and submit a PR, any pointers would be appreciated I'm just digging into the code now.

**Comment by raysrashmi** [comment]
Hey I have tried to get "special authentication privileges" but it think its hard to get this one. For now i added that email in to response in "ry-add-email-in-response" branch you can try out this  if it works we will merge this to master

**Comment by sunild** [comment]
Thanks for looking into this! I tried and your branch and took a look at the commit. 

The raw info that we get back from Twitter does not contain an email property. The change you made is necessary, but I believe something needs to happen in the request that is sent to Twitter, to tell them to include the email in the response (e.g. they told me to "Change your token's scope to request email").

I'm guessing that an "include_email" permission/parameter is required here in the [request_phase](https://github.com/arunagw/omniauth-twitter/blob/master/lib/omniauth/strategies/twitter.rb#L42). But it should probably be optional, so that it doesn't cause problems for apps that don't have this permission.

If you look at the Twitter Developer forum link, the very last post has an example of what I'm talking about ... but it's in python :) That thread is super long, [here is a link](https://twittercommunity.com/t/how-to-get-email-from-twitter-user-using-oauthtokens/558/201) that I think goes right to the post.

**Comment by raysrashmi** [comment]
I saw this here too https://dev.twitter.com/rest/reference/get/account/verify_credentials
Now I appended  the include_email in verify_credentials.json request. Try it out now :)

**Comment by sunild** [comment]
Hi it works, thank you so much! One slight change... you had `include_email=email` and it should be set to `true` instead :)

Also, this should be optional? Or it it safe for people w/out permissions?

**Comment by raysrashmi** [comment]
Ah right it should be true . 
Its optional parameter so it will work. 
Thanks
