### ISSUE TITLE
Not getting nicknames 

### ISSUE THREAD

**Issue by tommybstitch** [arunagw/omniauth-twitter#98]
I seem to be getting nothing returned for user nicknames for most of my users. I am checking the request.env['omniauth.auth']['info']['nickname'] variable and saving it as their username. 

I have a check in place to make sure it isn't returning nil and if it does, to save the ['name'] in place of the ['nickname'], but an empty string is getting saved, implying that some users' nicknames are returning as empty strings. 

Has anyone else ran into this?

**Comment by raysrashmi** [comment]
I tried it out its working. If you can provide some dummy code I will try to debug. Or you can ask on stackoverflow  if still not working for you

**Comment by tommybstitch** [comment]
I actually think this was a mistake on my end, my apologies, I forgot I had opened this issue. Will close with this comment, thanks!
